export const data: Work[] = [
 {
    price: "$630.44",
    duration: "283h 8m",
    like: "703",
    tag: "tag",
    work: "/work/work1.svg",
    title: "Punishment",
    subtitleArt: "Artist",
    subtitleGalery: "Galery",
    artist: "Marvin McKinney",
    galery: "Cameron Williamson",
  },
  {
    price: "$630.44",
    duration: "283h 8m",
    like: "703",
    tag: "tag",
    work: "/work/work2.svg",
    title: "Punishment",
    subtitleArt: "Artist",
    subtitleGalery: "Galery",
    artist: "Marvin McKinney",
    galery: "Cameron Williamson",
  },
   {
    price: "$630.44",
    duration: "283h 8m",
    like: "703",
    tag: "tag",
    work: "/work/work3.svg",
    title: "Punishment",
    subtitleArt: "Artist",
    subtitleGalery: "Galery",
    artist: "Marvin McKinney",
    galery: "Cameron Williamson",
  },
  {
    price: "$630.44",
    duration: "283h 8m",
    like: "703",
    tag: "tag",
    work: "/work/work4.svg",
    title: "Punishment",
    subtitleArt: "Artist",
    subtitleGalery: "Galery",
    artist: "Marvin McKinney",
    galery: "Cameron Williamson",
  },
   {
    price: "$630.44",
    duration: "283h 8m",
    like: "703",
    tag: "tag",
    work: "/work/work5.svg",
    title: "Punishment",
    subtitleArt: "Artist",
    subtitleGalery: "Galery",
    artist: "Marvin McKinney",
    galery: "Cameron Williamson",
  },
  {
    price: "$630.44",
    duration: "283h 8m",
    like: "703",
    tag: "tag",
    work: "/work/work6.svg",
    title: "Punishment",
    subtitleArt: "Artist",
    subtitleGalery: "Galery",
    artist: "Marvin McKinney",
    galery: "Cameron Williamson",
  },
   {
    price: "$630.44",
    duration: "283h 8m",
    like: "703",
    tag: "tag",
    work: "/work/work7.svg",
    title: "Punishment",
    subtitleArt: "Artist",
    subtitleGalery: "Galery",
    artist: "Marvin McKinney",
    galery: "Cameron Williamson",
  },
   {
    price: "$630.44",
    duration: "283h 8m",
    like: "703",
    tag: "tag",
    work: "/work/work8.svg",
    title: "Punishment",
    subtitleArt: "Artist",
    subtitleGalery: "Galery",
    artist: "Marvin McKinney",
    galery: "Cameron Williamson",
  },
  {
    price: "$630.44",
    duration: "283h 8m",
    like: "703",
    tag: "tag",
    work: "/work/work9.svg",
    title: "Punishment",
    subtitleArt: "Artist",
    subtitleGalery: "Galery",
    artist: "Marvin McKinney",
    galery: "Cameron Williamson",
  },
   {
    price: "$630.44",
    duration: "283h 8m",
    like: "703",
    tag: "tag",
    work: "/work/work10.svg",
    title: "Punishment",
    subtitleArt: "Artist",
    subtitleGalery: "Galery",
    artist: "Marvin McKinney",
    galery: "Cameron Williamson",
  },
   {
    price: "$630.44",
    duration: "283h 8m",
    like: "703",
    tag: "tag",
    title: "Punishment",
    work: "/work/work11.svg",
    subtitleArt: "Artist",
    subtitleGalery: "Galery",
    artist: "Marvin McKinney",
    galery: "Cameron Williamson",
  },
   {
    price: "$630.44",
    duration: "283h 8m",
    like: "703",
    tag: "tag",
    work: "/work/work12.svg",
    title: "Punishment",
    subtitleArt: "Artist",
    subtitleGalery: "Galery",
    artist: "Marvin McKinney",
    galery: "Cameron Williamson",
  },
];

export type Work = {
  price: string;
  duration: string;
  like: string;
  tag: string;
  work: string;
  title: string;
  subtitleArt: string;
  subtitleGalery: string;
  artist: string;
  galery: string;
};
